// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw109jTlaEJ-14CZnBGiu_LbQwz0bC7ak',
    appId: '1:7887139847:web:59658f25c100fa0f1166a2',
    messagingSenderId: '7887139847',
    projectId: 'chat-app-638ae',
    authDomain: 'chat-app-638ae.firebaseapp.com',
    storageBucket: 'chat-app-638ae.appspot.com',
    measurementId: 'G-GPZT5NKL6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfpQ9xn8OnlYEaMpD-oHnbg6avHGh-AIY',
    appId: '1:7887139847:android:3330ea42da260cf31166a2',
    messagingSenderId: '7887139847',
    projectId: 'chat-app-638ae',
    storageBucket: 'chat-app-638ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8Wzx4ir9i0F0_GuXA6sb8VWakq-3VrI',
    appId: '1:7887139847:ios:80ea6cec2da036901166a2',
    messagingSenderId: '7887139847',
    projectId: 'chat-app-638ae',
    storageBucket: 'chat-app-638ae.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr8Wzx4ir9i0F0_GuXA6sb8VWakq-3VrI',
    appId: '1:7887139847:ios:1e3195f6643e757d1166a2',
    messagingSenderId: '7887139847',
    projectId: 'chat-app-638ae',
    storageBucket: 'chat-app-638ae.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
